name: driver_app
description: Driver App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # البكجات المشتركة
  app_ui:
    path: ../packages/app_ui
  app_core:
    path: ../packages/app_core

  # (اختياري الآن – بنحتاجها قريباً)
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
