name: customer_app
description: Customer App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2

  google_maps_flutter: ^2.3.0
  location: ^4.4.0

  # البكج المشترك (UI)
  app_ui:
    path: ../packages/app_ui

  # اختياري (مفيد لاحقًا)
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2

flutter:
  uses-material-design: true
